### PR TITLE
Better support for campaign parameters behind hash tag (#) PPPDEV-421

### PR DESCRIPTION
**Pull request by adaqus**
* Better support for campaign parameters behind hash tag (#)
* Improved tests

### CODE REVIEW

**Comment by mattab** [comment]
@adaqus it looks like it was merged without review? maybe you discussed internally but it's important to see the `+1` by another reviewer before merging so we know for sure it was reviewed :+1:

**Comment by adaqus** [comment]
@mattab The review was done by @wronan, but he didn't want to put his comments here for some reason. He wrote his notices in private message.

**Comment by mattab** [comment]
ok! @wronan please remember to write +1 in pull request itself 

Fyi i've added a new test case i thought would be useful: https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/commit/c0c0debbe0e1777f4dc681336f110a1b0423a70a

**Comment by adaqus** [comment]
Ok, this is actually a case tests were lacking

**Pull request merged**
